export const KERALA_COLLEGES = [
    "Adi Shankara Institute of Engineering and Technology, Kalady",
    "Al-Ameen College, Edathala",
    "Amal Jyothi College of Engineering, Kanjirappally",
    "Amrita School of Medicine, Kochi",
    "Amrita Vishwa Vidyapeetham, Amritapuri",
    "APJ Abdul Kalam Technological University (KTU)",
    "Assumption College, Changanassery",
    "Ahalia School of Engineering and Technology, Palakkad",
    "Baselios Vidyanikethan College, Vaikom",
    "Bharat Mata College, Thrikkakara",
    "Bishop Moore College, Mavelikara",
    "Brennen College, Thalassery",
    "Calicut University",
    "Carmel College, Mala",
    "Catholicate College, Pathanamthitta",
    "Central University of Kerala, Kasaragod",
    "Chengannur College of Engineering",
    "Christian College, Chengannur",
    "CMS College, Kottayam",
    "Cochin University of Science and Technology (CUSAT)",
    "College of Engineering, Adoor",
    "College of Engineering, Aranmula",
    "College of Engineering, Attingal",
    "College of Engineering, Chengannur",
    "College of Engineering, Cherthala",
    "College of Engineering, Kallooppara",
    "College of Engineering, Karunagapally",
    "College of Engineering, Kidangoor",
    "College of Engineering, Kottarakkara",
    "College of Engineering, Munnar",
    "College of Engineering, Pathanapuram",
    "College of Engineering, Perumon",
    "College of Engineering, Poonjar",
    "College of Engineering, Thalassery",
    "College of Engineering, Thrikkakara",
    "College of Engineering, Trikaripur",
    "College of Engineering, Trivandrum (CET)",
    "College of Engineering, Vadakara",
    "Farook College, Kozhikode",
    "Fatima Mata National College, Kollam",
    "Federal Institute of Science and Technology (FISAT)",
    "Government Arts and Science College, Calicut",
    "Government College, Chittur",
    "Government College, Kasaragod",
    "Government College, Kottayam",
    "Government College, Madappally",
    "Government College, Mananthavady",
    "Government College, Tripunithura",
    "Government Engineering College, Barton Hill",
    "Government Engineering College, Idukki",
    "Government Engineering College, Kozhikode",
    "Government Engineering College, Palakkad",
    "Government Engineering College, Sreekrishnapuram",
    "Government Engineering College, Thrissur",
    "Government Engineering College, Wayanad",
    "Government Law College, Ernakulam",
    "Government Law College, Kozhikode",
    "Government Law College, Thrissur",
    "Government Law College, Trivandrum",
    "Government Medical College, Ernakulam",
    "Government Medical College, Kottayam",
    "Government Medical College, Kozhikode",
    "Government Medical College, Thrissur",
    "Government Medical College, Trivandrum",
    "Government Victoria College, Palakkad",
    "Gurudev Arts and Science College, Kannur",
    "IHRD College of Applied Science",
    "IISER Thiruvananthapuram",
    "IIST Thiruvananthapuram",
    "Indian Institute of Information Technology, Kottayam (IIITK)",
    "Indian Institute of Management, Kozhikode (IIMK)",
    "Indian Institute of Technology, Palakkad (IIT PKD)",
    "Jawaharlal College of Engineering and Technology, Lakkidi",
    "Jubilee Mission Medical College, Thrissur",
    "Jyothi Engineering College, Cheruthuruthy",
    "Kannur University",
    "KMEA Engineering College, Edathala",
    "Kerala Agricultural University (KAU)",
    "Kerala University of Fisheries and Ocean Sciences (KUFOS)",
    "Kerala University of Health Sciences (KUHS)",
    "LBS College of Engineering, Kasaragod",
    "LBS Institute of Technology for Women, Trivandrum",
    "Little Flower College, Guruvayur",
    "MA College of Engineering (MACE), Kothamangalam",
    "MES College of Engineering, Kuttippuram",
    "MES Mampad College",
    "MSM College, Kayamkulam",
    "Madappally Government College",
    "Maharaja's College, Ernakulam",
    "Mahatma Gandhi University (MGU), Kottayam",
    "Malabar Christian College, Kozhikode",
    "Malabar Medical College, Kozhikode",
    "Mar Athanasios College for Advanced Studies (MACFAST)",
    "Mar Baselios College of Engineering and Technology, Trivandrum",
    "Mar Ivanios College, Thiruvananthapuram",
    "Marian College, Kuttikkanam",
    "Mary Matha Arts & Science College, Mananthavady",
    "Mercy College, Palakkad",
    "Model Engineering College (MEC), Thrikkakara",
    "Mount Zion College of Engineering, Kadammanitta",
    "NSS College, Nemmara",
    "NSS College, Nilamel",
    "NSS College, Ottapalam",
    "NSS College, Pandalam",
    "NSS College of Engineering, Palakkad",
    "National Institute of Technology, Calicut (NITC)",
    "National University of Advanced Legal Studies (NUALS)",
    "Newman College, Thodupuzha",
    "Nirmala College, Muvattupuzha",
    "PSMO College, Tirurangadi",
    "Pazhassi Raja College, Pulpally",
    "Providence Women's College, Kozhikode",
    "Pushpagiri Medical College, Thiruvalla",
    "Rajagiri College of Social Sciences, Kalamassery",
    "Rajagiri School of Engineering & Technology (RSET), Kochi",
    "Rajiv Gandhi Institute of Technology (RIT), Kottayam",
    "SCT College of Engineering, Trivandrum",
    "SD College, Alappuzha",
    "Sahrdaya College of Engineering and Technology, Kodakara",
    "Saintgits College of Engineering, Kottayam",
    "SCMS School of Engineering and Technology, Kochi",
    "Sree Chitra Tirunal Institute for Medical Sciences and Technology",
    "Sree Krishna College, Guruvayur",
    "Sree Narayana College, Kannur",
    "Sree Narayana College, Kollam",
    "Sree Narayana College, Varkala",
    "Sree Sankaracharya University of Sanskrit, Kalady",
    "Sreepathy Institute of Management and Technology, Vavanoor",
    "St. Albert's College, Ernakulam",
    "St. Berchmans College, Changanassery",
    "St. Joseph's College, Devagiri",
    "St. Mary's College, Thrissur",
    "St. Teresa's College, Ernakulam",
    "St. Thomas College, Palai",
    "St. Thomas College, Thrissur",
    "TKMM College, Nangiarkulangara",
    "TKM College of Engineering, Kollam",
    "Toc H Institute of Science and Technology, Kochi",
    "Union Christian College (UC), Aluva",
    "University College, Thiruvananthapuram",
    "University of Calicut",
    "University of Kerala",
    "Vidya Academy of Science and Technology, Thrissur",
    "Vimala College, Thrissur",
    "Viswajyothi College of Engineering and Technology, Vazhakulam",
    "Zamorin's Guruvayurappan College, Kozhikode",
    "Other / Not Listed"
];
