export const KERALA_DEGREES = [
    "B.Tech - Computer Science & Engineering",
    "B.Tech - Electronics & Communication Engineering",
    "B.Tech - Mechanical Engineering",
    "B.Tech - Electrical & Electronics Engineering",
    "B.Tech - Civil Engineering",
    "B.Tech - Information Technology",
    "B.Tech - Chemical Engineering",
    "B.Tech - Biotech Engineering",
    "B.Arch - Architecture",
    "B.Sc - Computer Science",
    "B.Sc - Mathematics",
    "B.Sc - Physics",
    "B.Sc - Chemistry",
    "B.Sc - Botany",
    "B.Sc - Zoology",
    "B.Sc - Psychology",
    "B.Com - Finance & Taxation",
    "B.Com - Computer Applications",
    "B.Com - Co-operation",
    "B.A - English Literature",
    "B.A - Economics",
    "B.A - History",
    "B.A - Political Science",
    "BBA - Bachelor of Business Administration",
    "BCA - Bachelor of Computer Applications",
    "B.Ed - Bachelor of Education",
    "MBBS - Medicine and Surgery",
    "BDS - Dental Surgery",
    "B.Pharm - Pharmacy",
    "LL.B - Bachelor of Laws",
    "M.Tech - Computer Science",
    "M.Tech - Digital Electronics",
    "M.Sc - Computer Science",
    "M.Sc - Data Science",
    "M.Com",
    "MBA - Master of Business Administration",
    "MCA - Master of Computer Applications",
    "M.A - English",
    "Ph.D",
    "Other / Not Listed"
];
